" My gvimrc file
" Make external commands work through a pipe instead of a pseudo-tty
" set noguipty

" set the X11 font to use
" set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1

if has("win32")
  set guifont=Lucida_Console:h10:cDEFAULT
endif

set ch=2		" Make command line two lines high
set mousehide		" Hide the mouse when typing text

" Make shift-insert work like in Xterm
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

"set columns=130
"set lines=50 

if did_install_default_menus == 4
    unlet did_install_default_menus
    runtime menu.vim
endif

" Only do this for Vim version 5.0 and later.
if version >= 500

  " I like highlighting strings inside C comments
  let c_comment_strings=1

  " Switch on syntax highlighting if it wasn't on yet.
  if !exists("syntax_on")
    syntax on
  endif

  " Switch on search pattern highlighting.
  set hlsearch

  colorscheme industry

endif
